/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Institutional design system
        'primary': '#0F172A',
        'primary-container': '#131B2E',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#7C839B',
        'secondary': '#4648D4',
        'secondary-container': '#6063EE',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#FFFBFF',
        'surface': '#F8F9FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#EFF4FF',
        'surface-container': '#E5EEFF',
        'surface-container-high': '#DCE9FF',
        'surface-container-highest': '#D3E4FE',
        'on-surface': '#0B1C30',
        'on-surface-variant': '#45464D',
        'outline': '#76777D',
        'outline-variant': '#C6C6CD',
        'error': '#BA1A1A',
        'error-container': '#FFDAD6',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#EA F1FF',
        'tertiary': '#000000',
        'tertiary-container': '#002113',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#009668',
        'tertiary-fixed-dim': '#4EDEA3',
      },
      fontFamily: {
        'display-lg': ['Manrope', 'sans-serif'],
        'display-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'mono-data': ['Inter', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
      spacing: {
        'unit': '8px',
        'container-margin': '24px',
        'gutter': '16px',
        'section-gap': '32px',
        'tight': '4px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
    },
  },
  plugins: [],
}
